language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx-2.1.0
  - rbx-2.2.0
  - ree
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: 1.8.7
    - rvm: rbx-2.1.0
    - rvm: rbx-2.2.0
    - rvm: ree
